max_length: 160
vocab_size: 50000
min_freq: 2
embedding_dim: 200
channels: 128
kernels: [3, 4, 5]
hidden_dim: 256
dropout: 0.35
batch_size: 64
epochs: 20
patience: 4
lr: 0.001
weight_decay: 0.0001
label_smoothing: 0.05
max_grad_norm: 1.0

word_segmenter: pyvi
loss_type: focal
focal_gamma: 2.0
